ARG DEBIAN_VER
FROM docker-registry.wikimedia.org/python3-build-${DEBIAN_VER}:latest

USER root

RUN apt-get update && \
    apt-get -y --no-install-recommends install build-essential python3-dev libsasl2-dev

USER nobody

COPY freeze_requirements.sh /bin/freeze
