FROM docker-registry.wikimedia.org/python3-build-stretch:latest

RUN apt-get update && \
    apt-get -y --no-install-recommends install build-essential python3-dev \
        libsasl2-dev && \
    pip3 install --upgrade setuptools

COPY freeze_requirements.sh /bin/freeze
